enterprise-survey-2024.csv:
  validators:
    - type: duplicate
      columns:
        - Year
        - Industry_code_NZSIOC
        - Variable_code
    - type: datatype
      columns:
        Year: int
        Value: int
    - type: length
      columns:
        Industry_code_NZSIOC: 10
        Variable_code: 5
